sudo: false
dist: trusty
language: perl
python: "2.7.10"
perl:
  - "5.26"
  - "5.14"
addons:
  apt:
    packages:
    - libdb-dev
    - libgd2-noxpm-dev
  firefox: "58.0"
cache:
  - extlib/
  - $HOME/perl5/
before_install:
  #install geckodriver for the selenium tests :-P
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.19.1/geckodriver-v0.19.1-linux64.tar.gz
  - mkdir geckodriver
  - tar -xzf geckodriver-v0.19.1-linux64.tar.gz -C geckodriver
  - export PATH=$PATH:$PWD/geckodriver
  # install perl deps
  - cpanm --notest GD::Image Text::Markdown DateTime
  #- cpanm --notest git://github.com/bioperl/bioperl-live.git@v1.6.x
  # and jshint for the JS code
  - npm install -g jshint
install:
  - virtualenv ~/python
  - source ~/python/bin/activate
  - pip install nose selenium
  - bash setup.sh legacy
# NOTE: travis supports build stages and matrixes and stuff to implement this more symbolically,
# but the shell conditionals seem more straightforward for now
script:
  - jshint src/JBrowse/
  # if this is a release tag, then update both package.json files with the version in the tag
  - |
  if [[ "x$TRAVIS_TAG" != "x" ]]; then 
    build/insert_tag_version_into_package_jsons.pl src/JBrowse/package.json package.json
  fi
  # run tests in built release for builds on master, tags, or pull reqs, otherwise run tests in root
  - |
  if [[ "x$TRAVIS_TAG" != "x" || $TRAVIS_BRANCH = "master" || $TRAVIS_BRANCH = 'continuous_deployment' || $TRAVIS_PULL_REQUEST != "false" ]]; then
    make -f build/Makefile release;
    for zip in JBrowse-*.zip; do
      rm -rf JBrowse-*/;
      unzip JBrowse-*.zip;
      cp -r tests/ JBrowse-*/;
      cd JBrowse-*/
      ./setup.sh legacy;
      prove -Isrc/perl5 -r -j3 tests/perl_tests;
      ./jb_run.js -p 9000 &
      MOZ_HEADLESS=1 SELENIUM_BROWSER=firefox JBROWSE_URL=http://localhost:9000/index.html nosetests tests/selenium_tests/;
      killall jb_run.js;
    done;
  else
    ./jb_run.js -p 9000 &
    prove -j4 -Isrc/perl5 -lr tests/perl_tests
    MOZ_HEADLESS=1 SELENIUM_BROWSER=firefox JBROWSE_URL=http://localhost:9000/index.html nosetests tests/selenium_tests/
  fi
  # if this is a release tag, then upload the built release to github releases
  - |
  if [[ "x$TRAVIS_TAG" != "x" ]]; then 
    #TODO
  fi

after_failure:
  - cat JBrowse-*-dev/setup.log 
  - find JBrowse-*-dev/extlib/lib/perl5
  - cat JBrowse-*-dev/src/build-report.txt
